repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: '\.(pdb|gro|top|sdf)$'
- repo: https://github.com/psf/black
  rev: 21.5b2
  hooks:
  - id: black
    files: ^openff
    args: [--check]
- repo: https://github.com/PyCQA/isort
  rev: 5.8.0
  hooks:
  - id: isort
    files: ^openff
    args: [--check]
- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    files: ^openff
    additional_dependencies: [
        'flake8-bugbear',
        'flake8-absolute-import',
    ]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.1
  hooks:
  - id: pyupgrade
    files: ^openff/system/
    exclude: openff/system/_version.py|setup.py
    args: [--py37-plus]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.11.1
  hooks:
    - id: nbqa-pyupgrade
      args:
        - --nbqa-mutate
        - --py37-plus
    - id: nbqa-isort
      args:
        - --nbqa-mutate
    - id: nbqa-black
      args:
        - --nbqa-mutate
