name: openff-interchange-docs
channels:
  - conda-forge
dependencies:
  # Base depends
  - python
  - pip
  - pydantic
  - pint
  - openmm
  - openff-toolkit
  - jax
  - ele
  # readthedocs dependencies
  - myst-parser
  - numpydoc
    - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
