name: Nightly tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      CI_OS: ${{ matrix.os }}
      PYVER: ${{ matrix.python-version }}
      COV: --cov=openff/interchange --cov-report=xml --cov-config=setup.cfg --cov-append

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/test_env.yaml
        activate-environment: test
        auto-activate-base: false
        mamba-version: "*"
        miniforge-version: latest
        miniforge-variant: Mambaforge
        use-mamba: true

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install package
      shell: bash -l {0}
      run: |
        python setup.py develop --no-deps

    - name: Run mypy
      continue-on-error: true
      shell: bash -l {0}
      run: |
        mypy --show-error-codes --namespace-packages -p "openff.interchange"

    - name: Run all tests
      if: always()
      shell: bash -l {0}
      run: |
        python -m pytest -v $COV openff/interchange/

    - name: Run example notebooks
      shell: bash -l {0}
      run: |
        python -m pytest -v $COV examples/ --nbval-lax

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
